feature/ST-30/superAdmin
Tilajc/SubasTodo-Server pull request #6
Opened 2023-10-20 02:02 UTC by Milicerro

I worked on the model, controller, validations and routes of Super Admin entity. I have tested the differents endpoints in postman.

2023-10-21 18:53 UTC, Tilajc commented on src/controllers/super-admin.js
> +      message: 'An Error ocurred',
```suggestion
      message: `An error ocurred: ${error}`,
```

2023-10-21 18:56 UTC, Tilajc commented on src/controllers/super-admin.js
> +      message: 'An error occurred',
```suggestion
      message: `An error ocurred: ${error}`,
```

2023-10-21 18:58 UTC, Tilajc requested changes
It's almost done! just two comments for consistence. Pretty good job!

2023-10-26 22:06 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Super-admin entity](https://trello.com/c/bQRLx0rv/30-super-admin-entity)

2023-10-30 02:21 UTC, LucianoStradiot approved these changes
LG!

2023-10-30 14:29 UTC, Tilajc approved these changes

2023-10-31 23:29 UTC, merged