ST-7/Bid-Entity
Tilajc/SubasTodo-Server pull request #7
Opened 2023-10-26 15:11 UTC by Tilajc

I created the bid entity api

2023-10-26 17:48 UTC, VictoriaNegrotto approved these changes
I think it's good

2023-10-26 22:06 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bid Entity](https://trello.com/c/XLMaSyuh/7-bid-entity)

2023-10-27 14:34 UTC, LucianoStradiot requested changes
Looks good to me. Just look at the comments that I left to see if you agree with me.

2023-10-27 14:34 UTC, LucianoStradiot commented on src/controllers/bid.js
> +      message: 'invalid bidOwner ID',
Please Mayus on the first letter

2023-10-27 14:34 UTC, LucianoStradiot commented on src/controllers/bid.js
> +        message: 'Cannot find the owner user',
Here you could refer to the user´s name so it can show which user is

2023-10-27 14:34 UTC, LucianoStradiot commented on src/controllers/bid.js
> +      message: 'invalid ID',
Mayus on the first letter

2023-10-27 14:34 UTC, LucianoStradiot commented on src/controllers/bid.js
> +      message: 'Invalid bidWinner ID',
This it will be better if the bidWinner it´s replaced by "winner" or someone like that because it´s the message that will show to the user

2023-10-27 14:34 UTC, LucianoStradiot commented on src/controllers/bid.js
> +        message: `The bidWinner with the ID: ${bidWinner} doesn't exists`,
Same here

2023-10-27 14:34 UTC, LucianoStradiot commented on src/validations/bid.js
> +      })
Here it would be good that there is a validation so that the user can put a maximum of photos.

2023-10-27 14:34 UTC, LucianoStradiot commented on src/validations/bid.js
> +      'number.min': 'Price cant be less than 0'
missing validation for empty field

2023-10-27 14:34 UTC, LucianoStradiot commented on src/validations/bid.js
> +      .required(),
This validation I´m not sure if it´s right because the user that creates the bid it´s already logged

2023-10-27 23:14 UTC, LucianoStradiot approved these changes
LG

2023-10-27 23:14 UTC, merged