Feature/st 29/question
Tilajc/SubasTodo-Server pull request #8
Opened 2023-10-27 22:49 UTC by VictoriaNegrotto

Changed to question. Finished validations, controllers, routes, models.

2023-10-27 22:50 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Products entity](https://trello.com/c/3eeZjERI/29-products-entity)

2023-10-27 23:16 UTC, Tilajc commented on src/controllers/question.js
> +//import Bid from '../models/Bid';
```suggestion

```

2023-10-27 23:31 UTC, Tilajc commented on src/controllers/question.js
> +  try {
```suggestion
  if(!mongoose.isValidObjectId){
     return res.....
  }
  try {
```

2023-10-27 23:33 UTC, Tilajc commented on src/controllers/question.js
> +      message: `Question with ID ${idQuestion.id} was found!`,
Here the ID is enough to show

```suggestion
      message: `Question with ID ${id} was found!`,
```

2023-10-27 23:35 UTC, Tilajc commented on src/controllers/question.js
> +      message: `Question with ID ${newQuestion.id} created!`,
```suggestion
      message: 'Question created succesfully',
```

2023-10-27 23:36 UTC, Tilajc commented on src/controllers/question.js
> +        message: `Question with id: ${id} was not found`,
```suggestion
        message: `Question with ID: ${id} was not found`,
```

2023-10-27 23:37 UTC, Tilajc commented on src/controllers/question.js
> +        message: `Question with ID ${id} was not found`,
```suggestion
        message: `Question with ID: ${id} was not found`,
```

2023-10-27 23:38 UTC, Tilajc commented on src/controllers/question.js
> +      message: error,
```suggestion
      message: `An error ocurred: ${error}`,
```

2023-10-27 23:38 UTC, Tilajc commented on src/controllers/question.js
> +      message: error,
```suggestion
      message: `An error ocurred: ${error}`,
```

2023-10-27 23:46 UTC, Tilajc commented on src/validations/question.js
> +const validateupdateQuestion = (req, res, next) => {
```suggestion
const validateUpdateQuestion = (req, res, next) => {
```

2023-10-27 23:47 UTC, Tilajc requested changes
Pretty good job, the job is almost done, just little comments for consistence!

2023-10-30 02:26 UTC, LucianoStradiot requested changes
With the tila´s correction It should be finished

2023-10-30 03:43 UTC, LucianoStradiot approved these changes
LG!

2023-10-30 14:31 UTC, Tilajc approved these changes

2023-10-30 23:34 UTC, merged